# Dynamic Asset Pricing Model Configuration
# This file contains all configurable parameters for the model

volatility:
  k1: 1.5          # Pre-event volatility scaling
  k2: 2.0          # Post-event volatility scaling (k2 > k1)
  delta_t1: 5.0    # Pre-event duration (days)
  delta_t2: 3.0    # Rising phase duration (days)
  delta_t3: 10.0   # Decay phase duration (days)
  delta: 5.0       # General delta parameter

optimization:
  gamma_T: 2.0           # Terminal wealth risk aversion
  gamma_V: 1.0           # Real-time variance aversion
  risk_free_rate: 0.0    # Risk-free rate
  optimistic_bias: 0.01  # Optimistic bias parameter

transaction_costs:
  tau_b: 0.001   # Purchase transaction cost
  tau_s: 0.0005  # Sale transaction cost (must be <= tau_b)

data:
  # Development environment settings
  use_mock_data: true
  mock_events: 1000
  mock_assets: 50
  
  # Production data paths (used when use_mock_data: false)
  stock_files: []
  fda_events: null
  earnings_events: null
  
  # Analysis parameters
  window_days: 30
  analysis_window: [-15, 15]

ml:
  # XGBoost parameters
  xgb_params:
    n_estimators: 100
    max_depth: 5
    learning_rate: 0.1
    objective: 'reg:squarederror'
    subsample: 0.8
    colsample_bytree: 0.8
    random_state: 42
    n_jobs: -1
  
  # Ensemble parameters
  ensemble_weight: 0.5
  n_deciles: 10
  alpha: 0.1
  lambda_smooth: 0.1

simulation:
  n_simulations: 1000
  n_steps: 252          # Trading days in a year
  parallel_processing: true
  random_seed: 42